export const tabList = [
    { label: 'По проекту', href: '/project/0/about', fullname:'' },
    { label: 'Объекты', href: '/project/0/objects', fullname:'' },
    { label: 'РД', href: '/project/0/rd', fullname:'' },
    { label: 'МТО', href: '/project/0/mto', fullname:'Материально-техническое обеспечение' },
    { label: 'СМР', href: '/project/0/cmr', fullname:'Строительно-монтажные работы' },
    { label: 'График', href: '/project/0/graphic', fullname:'' },
    { label: 'МиМ', href: '/project/0/mim', fullname:'' },
    { label: 'Рабочие', href: '/project/0/staff', fullname:'' },
    { label: 'Капвложения', href: '/project/0/capital-invesments', fullname:'' },
    { label: 'Бюджет', href: '/project/0/budget', fullname:'' },
    { label: 'Финансирование', href: '/project/0/financing', fullname:'' },
    { label: 'Панорамы', href: '/project/0/panoramas', fullname:'' },
    { label: 'Камеры', href: '/project/0/cameras', fullname:'' },
    { label: 'Поручения', href: '/project/0/orders', fullname:'' },
    { label: 'Контрагенты', href: '/project/0/counterparties', fullname:'' },
];